/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
import java.awt.Color;
import javax.swing.JOptionPane;
public class HitungDiskonFrame extends javax.swing.JFrame {

    /**
     * Creates new form HitungDiskonFrame
     */
    public HitungDiskonFrame() {
        initComponents();
        setLocationRelativeTo(null);
        // Placeholder untuk harga asli
        txtHarga.setText("Masukkan harga asli");
        txtHarga.setForeground(Color.GRAY);
        txtHarga.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtHarga.getForeground().equals(Color.GRAY)) {
                    txtHarga.setText("");
                    txtHarga.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtHarga.getText().isEmpty()) {
                    txtHarga.setText("Masukkan harga asli");
                    txtHarga.setForeground(Color.GRAY);
                }
            }
        });

        // Placeholder untuk kupon
        txtKupon.setText("Masukkan kode kupon (opsional)");
        txtKupon.setForeground(Color.GRAY);
        txtKupon.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtKupon.getForeground().equals(Color.GRAY)) {
                    txtKupon.setText("");
                    txtKupon.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtKupon.getText().isEmpty()) {
                    txtKupon.setText("Masukkan kode kupon (opsional)");
                    txtKupon.setForeground(Color.GRAY);
                }
            }
        });

        // Text hasil tidak bisa diketik
        txtHasil.setEditable(false);
        txtHasil.setForeground(Color.GRAY);
        jTextAreaRiwayat.setEditable(false);
        
        // Placeholder untuk penghematan
        txtPenghematan.setText("Penghematan akan muncul di sini");
        txtPenghematan.setForeground(Color.GRAY);
        txtPenghematan.setEditable(false);
        
        // Placeholder untuk hasil harga akhir
        txtHasil.setText("Harga akhir akan muncul di sini");
        txtHasil.setForeground(Color.GRAY);

        // Atur fokus awal bukan ke textfield
        java.awt.EventQueue.invokeLater(() -> {
            panelHitungDiskon.requestFocusInWindow();
        });
        // --- Sinkronisasi antara ComboBox dan Slider Diskon ---
        sldrDiskon.addChangeListener(e -> {
            int value = sldrDiskon.getValue();
            if (value % 5 == 0) { // hanya tangkap nilai kelipatan 5
                cmbDiskon.setSelectedItem(value == 0 ? "-" : value + "%");
            }
        });

        cmbDiskon.addActionListener(e -> {
            String selected = (String) cmbDiskon.getSelectedItem();
            if (!selected.equals("-")) {
                int val = Integer.parseInt(selected.replace("%", ""));
                sldrDiskon.setValue(val);
            } else {
                sldrDiskon.setValue(0);
            }
        });
        // Tampilkan label angka di bawah slider
        java.util.Hashtable<Integer, javax.swing.JLabel> labelTable = new java.util.Hashtable<>();
        for (int i = 0; i <= 25; i += 5) {
            labelTable.put(i, new javax.swing.JLabel(String.valueOf(i)));
        }
        sldrDiskon.setLabelTable(labelTable);
        sldrDiskon.setPaintLabels(true);
        sldrDiskon.setValue(0);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        panelHitungDiskon = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblHargaAsli = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        lblKupon = new javax.swing.JLabel();
        lblHargaAkhir = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        cmbDiskon = new javax.swing.JComboBox<>();
        lblRiwayat = new javax.swing.JLabel();
        scrlRiwayat = new javax.swing.JScrollPane();
        jTextAreaRiwayat = new javax.swing.JTextArea();
        btnHitung = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtKupon = new javax.swing.JTextField();
        txtHasil = new javax.swing.JTextField();
        sldrDiskon = new javax.swing.JSlider();
        lblHemat = new javax.swing.JLabel();
        txtPenghematan = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perhitungan Diskon");

        panelHitungDiskon.setBackground(new java.awt.Color(52, 73, 94));
        panelHitungDiskon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("APLIKASI PERHITUNGAN DISKON");

        lblHargaAsli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHargaAsli.setForeground(new java.awt.Color(255, 255, 255));
        lblHargaAsli.setText("HARGA ASLI:");

        lblDiskon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDiskon.setForeground(new java.awt.Color(255, 255, 255));
        lblDiskon.setText("PILIH DISKON:");

        lblKupon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKupon.setForeground(new java.awt.Color(255, 255, 255));
        lblKupon.setText("KODE KUPON:");

        lblHargaAkhir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHargaAkhir.setForeground(new java.awt.Color(255, 255, 255));
        lblHargaAkhir.setText("HARGA AKHIR:");

        cmbDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "5%", "10%", "15%", "20%", "25%" }));

        lblRiwayat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRiwayat.setForeground(new java.awt.Color(255, 255, 255));
        lblRiwayat.setText("RIWAYAT PERHITUNGAN:");

        jTextAreaRiwayat.setColumns(20);
        jTextAreaRiwayat.setRows(5);
        scrlRiwayat.setViewportView(jTextAreaRiwayat);

        btnHitung.setBackground(new java.awt.Color(0, 204, 0));
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 204, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(204, 51, 0));
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        sldrDiskon.setForeground(new java.awt.Color(255, 255, 255));
        sldrDiskon.setMajorTickSpacing(5);
        sldrDiskon.setMaximum(25);
        sldrDiskon.setPaintLabels(true);
        sldrDiskon.setPaintTicks(true);

        lblHemat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHemat.setForeground(new java.awt.Color(255, 255, 255));
        lblHemat.setText("PENGHEMATAN:");

        txtPenghematan.setEditable(false);

        javax.swing.GroupLayout panelHitungDiskonLayout = new javax.swing.GroupLayout(panelHitungDiskon);
        panelHitungDiskon.setLayout(panelHitungDiskonLayout);
        panelHitungDiskonLayout.setHorizontalGroup(
            panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHitungDiskonLayout.createSequentialGroup()
                .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHitungDiskonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrlRiwayat))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelHitungDiskonLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHitungDiskonLayout.createSequentialGroup()
                                .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDiskon)
                                    .addComponent(lblHargaAsli)
                                    .addComponent(lblKupon)
                                    .addComponent(lblHargaAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblHemat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHasil, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtKupon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelHitungDiskonLayout.createSequentialGroup()
                                        .addComponent(cmbDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sldrDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 9, Short.MAX_VALUE))
                                    .addComponent(txtPenghematan)))
                            .addGroup(panelHitungDiskonLayout.createSequentialGroup()
                                .addComponent(lblRiwayat)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelHitungDiskonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelHitungDiskonLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHitungDiskonLayout.setVerticalGroup(
            panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHitungDiskonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHargaAsli)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHitungDiskonLayout.createSequentialGroup()
                        .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiskon)
                            .addComponent(cmbDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHitungDiskonLayout.createSequentialGroup()
                        .addComponent(sldrDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKupon)
                    .addComponent(txtKupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHargaAkhir)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPenghematan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHemat))
                .addGap(20, 20, 20)
                .addComponent(lblRiwayat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHitungDiskonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelHitungDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelHitungDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
                try {
        // Validasi input harga
        String hargaInput = txtHarga.getText().trim();
        if (hargaInput.isEmpty() || txtHarga.getForeground().equals(Color.GRAY)) {
            JOptionPane.showMessageDialog(this, "Masukkan harga asli terlebih dahulu!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Hapus titik (.) agar bisa diproses sebagai angka
        hargaInput = hargaInput.replace(".", "");
        double hargaAsli = Double.parseDouble(hargaInput);

        // Ambil diskon dari combo box dan ubah jadi angka
        String diskonStr = (String) cmbDiskon.getSelectedItem();
        int diskon = 0;
        if (!diskonStr.equals("-")) {
            diskonStr = diskonStr.replace("%", "");
            diskon = Integer.parseInt(diskonStr);
        }

        // Ambil kode kupon
        String kupon = txtKupon.getText().trim();
        double tambahan = 0;
        if (kupon.equalsIgnoreCase("HEMAT10")) {
            tambahan = 10;
        } else if (!kupon.isEmpty() && !txtKupon.getForeground().equals(Color.GRAY)) {
            JOptionPane.showMessageDialog(this, "Kode kupon tidak valid! (Gunakan: HEMAT10)",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
        }

        // Hitung total diskon dan harga akhir
        double totalDiskon = diskon + tambahan;
        double penghematan = hargaAsli * totalDiskon / 100;
        double hargaAkhir = hargaAsli - penghematan;

        // Format ke bentuk rupiah
        java.text.NumberFormat rupiahFormat = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
        String hasilRupiah = rupiahFormat.format(hargaAkhir);
        String hargaRupiah = rupiahFormat.format(hargaAsli);
        
        java.time.LocalDateTime now = java.time.LocalDateTime.now();
        java.time.format.DateTimeFormatter fmt = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String waktu = now.format(fmt);

        // Tampilkan hasil
        txtHasil.setForeground(Color.BLACK);
        txtHasil.setText(hasilRupiah);
        
        // Tampilkan penghematan
        txtPenghematan.setForeground(Color.BLACK);
        txtPenghematan.setText("Anda hemat " + rupiahFormat.format(penghematan));

        // Tambahkan ke riwayat
        jTextAreaRiwayat.append(
        "-------------------------------------------\n" +
        "Harga Asli     : " + hargaRupiah + "\n" +
        "Diskon         : " + diskon + "%\n" +
        (tambahan > 0 ? "Kupon          : HEMAT10 (+" + tambahan + "%)\n" : "") +
        "Total Diskon   : " + totalDiskon + "%\n" +
        "Penghematan    : " + rupiahFormat.format(penghematan) + "\n" +
        "Harga Akhir    : " + hasilRupiah + "\n" +
        "Dihitung pada : " + waktu + "\n" +
        "-------------------------------------------\n"       
        );

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk harga!",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Hapus semua data dan riwayat?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            txtHarga.setText("Masukkan harga asli");
            txtHarga.setForeground(Color.GRAY);
            txtKupon.setText("Masukkan kode kupon (opsional)");
            txtKupon.setForeground(Color.GRAY);
            txtHasil.setText("Harga akhir akan muncul di sini");
            txtHasil.setForeground(Color.GRAY);
            jTextAreaRiwayat.setText("");
            cmbDiskon.setSelectedIndex(0);
            sldrDiskon.setValue(0);
            txtPenghematan.setText("Penghematan akan muncul di sini");
            txtPenghematan.setForeground(Color.GRAY);
            
        }

        

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        
        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar dari aplikasi?",
                "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Terima kasih telah menggunakan aplikasi ini!");
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HitungDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HitungDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HitungDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HitungDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HitungDiskonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JComboBox<String> cmbDiskon;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextArea jTextAreaRiwayat;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblHargaAkhir;
    private javax.swing.JLabel lblHargaAsli;
    private javax.swing.JLabel lblHemat;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKupon;
    private javax.swing.JLabel lblRiwayat;
    private javax.swing.JPanel panelHitungDiskon;
    private javax.swing.JScrollPane scrlRiwayat;
    private javax.swing.JSlider sldrDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtKupon;
    private javax.swing.JTextField txtPenghematan;
    // End of variables declaration//GEN-END:variables
}
