/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
import java.awt.Color;
import javax.swing.JOptionPane;
public class HitungDiskonFrame extends javax.swing.JFrame {

    /**
     * Creates new form HitungDiskonFrame
     */
    public HitungDiskonFrame() {
        initComponents();
        setLocationRelativeTo(null);
        // Placeholder untuk harga asli
        jTextFieldHarga.setText("Masukkan harga asli");
        jTextFieldHarga.setForeground(Color.GRAY);
        jTextFieldHarga.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextFieldHarga.getForeground().equals(Color.GRAY)) {
                    jTextFieldHarga.setText("");
                    jTextFieldHarga.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextFieldHarga.getText().isEmpty()) {
                    jTextFieldHarga.setText("Masukkan harga asli");
                    jTextFieldHarga.setForeground(Color.GRAY);
                }
            }
        });

        // Placeholder untuk kupon
        jTextFieldKupon.setText("Masukkan kode kupon (opsional)");
        jTextFieldKupon.setForeground(Color.GRAY);
        jTextFieldKupon.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextFieldKupon.getForeground().equals(Color.GRAY)) {
                    jTextFieldKupon.setText("");
                    jTextFieldKupon.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextFieldKupon.getText().isEmpty()) {
                    jTextFieldKupon.setText("Masukkan kode kupon (opsional)");
                    jTextFieldKupon.setForeground(Color.GRAY);
                }
            }
        });

        // Text hasil tidak bisa diketik
        jTextFieldHasil.setEditable(false);
        jTextFieldHasil.setForeground(Color.GRAY);
        jTextAreaRiwayat.setEditable(false);
        
        // Placeholder untuk penghematan
        jTextFieldPenghematan.setText("Penghematan akan muncul di sini");
        jTextFieldPenghematan.setForeground(Color.GRAY);
        jTextFieldPenghematan.setEditable(false);
        
        // Placeholder untuk hasil harga akhir
        jTextFieldHasil.setText("Harga akhir akan muncul di sini");
        jTextFieldHasil.setForeground(Color.GRAY);

        // Atur fokus awal bukan ke textfield
        java.awt.EventQueue.invokeLater(() -> {
            jPanel1.requestFocusInWindow();
        });
        // --- Sinkronisasi antara ComboBox dan Slider Diskon ---
        jSliderDiskon.addChangeListener(e -> {
            int value = jSliderDiskon.getValue();
            if (value % 5 == 0) { // hanya tangkap nilai kelipatan 5
                jComboBoxDiskon.setSelectedItem(value == 0 ? "-" : value + "%");
            }
        });

        jComboBoxDiskon.addActionListener(e -> {
            String selected = (String) jComboBoxDiskon.getSelectedItem();
            if (!selected.equals("-")) {
                int val = Integer.parseInt(selected.replace("%", ""));
                jSliderDiskon.setValue(val);
            } else {
                jSliderDiskon.setValue(0);
            }
        });
        // Tampilkan label angka di bawah slider
        java.util.Hashtable<Integer, javax.swing.JLabel> labelTable = new java.util.Hashtable<>();
        for (int i = 0; i <= 25; i += 5) {
            labelTable.put(i, new javax.swing.JLabel(String.valueOf(i)));
        }
        jSliderDiskon.setLabelTable(labelTable);
        jSliderDiskon.setPaintLabels(true);
        jSliderDiskon.setValue(0);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();
        jComboBoxDiskon = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRiwayat = new javax.swing.JTextArea();
        jButtonHitung = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jTextFieldKupon = new javax.swing.JTextField();
        jTextFieldHasil = new javax.swing.JTextField();
        jSliderDiskon = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPenghematan = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APLIKASI PERHITUNGAN DISKON");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HARGA ASLI:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PILIH DISKON:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KODE KUPON:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HARGA AKHIR:");

        jComboBoxDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "5%", "10%", "15%", "20%", "25%" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RIWAYAT PERHITUNGAN:");

        jTextAreaRiwayat.setColumns(20);
        jTextAreaRiwayat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRiwayat);

        jButtonHitung.setBackground(new java.awt.Color(0, 204, 0));
        jButtonHitung.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHitung.setText("HITUNG");
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });

        jButtonHapus.setBackground(new java.awt.Color(255, 204, 0));
        jButtonHapus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHapus.setText("HAPUS");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonKeluar.setBackground(new java.awt.Color(204, 51, 0));
        jButtonKeluar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKeluar.setText("KELUAR");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        jTextFieldHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasilActionPerformed(evt);
            }
        });

        jSliderDiskon.setForeground(new java.awt.Color(255, 255, 255));
        jSliderDiskon.setMajorTickSpacing(5);
        jSliderDiskon.setMaximum(25);
        jSliderDiskon.setPaintLabels(true);
        jSliderDiskon.setPaintTicks(true);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PENGHEMATAN:");

        jTextFieldPenghematan.setEditable(false);
        jTextFieldPenghematan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPenghematanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldHasil, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldKupon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 9, Short.MAX_VALUE))
                                    .addComponent(jTextFieldPenghematan)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldKupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPenghematan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHitung)
                    .addComponent(jButtonHapus)
                    .addComponent(jButtonKeluar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHasilActionPerformed

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        // TODO add your handling code here:
        try {
        // Validasi input harga
        String hargaInput = jTextFieldHarga.getText().trim();
        if (hargaInput.isEmpty() || jTextFieldHarga.getForeground().equals(Color.GRAY)) {
            JOptionPane.showMessageDialog(this, "Masukkan harga asli terlebih dahulu!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Hapus titik (.) agar bisa diproses sebagai angka
        hargaInput = hargaInput.replace(".", "");
        double hargaAsli = Double.parseDouble(hargaInput);

        // Ambil diskon dari combo box dan ubah jadi angka
        String diskonStr = (String) jComboBoxDiskon.getSelectedItem();
        int diskon = 0;
        if (!diskonStr.equals("-")) {
            diskonStr = diskonStr.replace("%", "");
            diskon = Integer.parseInt(diskonStr);
        }

        // Ambil kode kupon
        String kupon = jTextFieldKupon.getText().trim();
        double tambahan = 0;
        if (kupon.equalsIgnoreCase("HEMAT10")) {
            tambahan = 10;
        } else if (!kupon.isEmpty() && !jTextFieldKupon.getForeground().equals(Color.GRAY)) {
            JOptionPane.showMessageDialog(this, "Kode kupon tidak valid! (Gunakan: HEMAT10)",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
        }

        // Hitung total diskon dan harga akhir
        double totalDiskon = diskon + tambahan;
        double penghematan = hargaAsli * totalDiskon / 100;
        double hargaAkhir = hargaAsli - penghematan;

        // Format ke bentuk rupiah
        java.text.NumberFormat rupiahFormat = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
        String hasilRupiah = rupiahFormat.format(hargaAkhir);
        String hargaRupiah = rupiahFormat.format(hargaAsli);
        
        java.time.LocalDateTime now = java.time.LocalDateTime.now();
        java.time.format.DateTimeFormatter fmt = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String waktu = now.format(fmt);

        // Tampilkan hasil
        jTextFieldHasil.setForeground(Color.BLACK);
        jTextFieldHasil.setText(hasilRupiah);
        
        // Tampilkan penghematan
        jTextFieldPenghematan.setForeground(Color.BLACK);
        jTextFieldPenghematan.setText("Anda hemat " + rupiahFormat.format(penghematan));

        // Tambahkan ke riwayat
        jTextAreaRiwayat.append(
        "-------------------------------------------\n" +
        "Harga Asli     : " + hargaRupiah + "\n" +
        "Diskon         : " + diskon + "%\n" +
        (tambahan > 0 ? "Kupon          : HEMAT10 (+" + tambahan + "%)\n" : "") +
        "Total Diskon   : " + totalDiskon + "%\n" +
        "Penghematan    : " + rupiahFormat.format(penghematan) + "\n" +
        "Harga Akhir    : " + hasilRupiah + "\n" +
        "Dihitung pada : " + waktu + "\n" +
        "-------------------------------------------\n"       
        );

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk harga!",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Hapus semua data dan riwayat?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            jTextFieldHarga.setText("Masukkan harga asli");
            jTextFieldHarga.setForeground(Color.GRAY);
            jTextFieldKupon.setText("Masukkan kode kupon (opsional)");
            jTextFieldKupon.setForeground(Color.GRAY);
            jTextFieldHasil.setText("Harga akhir akan muncul di sini");
            jTextFieldHasil.setForeground(Color.GRAY);
            jTextAreaRiwayat.setText("");
            jComboBoxDiskon.setSelectedIndex(0);
            jSliderDiskon.setValue(0);
            jTextFieldPenghematan.setText("Penghematan akan muncul di sini");
            jTextFieldPenghematan.setForeground(Color.GRAY);
            
        }

        

    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar dari aplikasi?",
                "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Terima kasih telah menggunakan aplikasi ini!");
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jTextFieldPenghematanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPenghematanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPenghematanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HitungDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HitungDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HitungDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HitungDiskonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HitungDiskonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBoxDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderDiskon;
    private javax.swing.JTextArea jTextAreaRiwayat;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldHasil;
    private javax.swing.JTextField jTextFieldKupon;
    private javax.swing.JTextField jTextFieldPenghematan;
    // End of variables declaration//GEN-END:variables
}
